src/CVaS.Web/Controllers/Api/AlgorithmsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using CVaS.BL.DTO;
using CVaS.BL.Facades;
using CVaS.Shared.Services.Process;
using CVaS.Web.Providers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace CVaS.Web.Controllers.Api
{
    [Route("[controller]")]
    public class AlgorithmsController : ApiController
    {
        private readonly ILogger<AlgorithmsController> _logger;
        private readonly RunFacade _runFacade;
        private readonly AlgorithmFacade _algoFacade;
        private readonly IEnumerable<IArgumentParser> _argumentParserProviders;

        public AlgorithmsController(ILogger<AlgorithmsController> logger, RunFacade runFacade, AlgorithmFacade algoFacade,
            IEnumerable<IArgumentParser> argumentParserProviders)
        {
            _logger = logger;
            _runFacade = runFacade;
            _algoFacade = algoFacade;
            _argumentParserProviders = argumentParserProviders;
        }

        /// <summary>
        /// Start process with given algorithm name and with given options. Returns
        /// result of the process.
        /// </summary>
        /// <param name="codeName">CodeName of the algorithm to be run.</param>
        /// <param name="options">Options are translated to command-line arguments. Expected
        /// format is json containing one element or single array with simple types or dictionary with
        /// only simple types</param>
        /// <param name="timeout">Specifies maximum amount of time to wait for returning request. If timeout
        /// is set to negative number, wait time is set to maximum possible time.</param>
        [HttpPost("{codeName}")]
        [Produces(typeof(RunDTO))]
        public async Task<IActionResult> Process(string codeName, [FromBody] object options, [FromQuery] int? timeout)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest();
            }

            var parser = _argumentParserProviders.FirstOrDefault(p => p.CanParse(options));

            if (parser == null)
            {
                return new UnsupportedMediaTypeResult();
            }

            List<object> parsedOptions;
            try
            {
                parsedOptions = parser.Parse(options);
            }
            catch (Exception)
            {
                ModelState.AddModelError(nameof(options), "Arguments are in bad format. Look at documentation");
                return BadRequest(ModelState);
            }

            var result = await _runFacade.RunAlgorithmAsync(codeName, parsedOptions, timeout);

            return this.CreatedAtAction<RunsController>(c => c.Get(With.No<Guid>()), new { runId = result.RunId },
                new RunDTO
                {
                    Id = result.RunId,
                    StdOut = result.StdOut,
                    StdErr = result.StdErr,
                    File = result.FileId != null ? Url.Link(nameof(FilesController.GetFile), new { fileId = result.FileId }) : null,
                    Status = result.Result,
                    CreatedAt = result.CreatedAt,
                    FinishedAt = result.FinishedAt
                });
        }

        /// <summary>
        /// Retrieve all algortihms hosted on server.
        /// </summary>
        /// <returns></returns>
        [HttpGet("")]
        [Produces(typeof(IEnumerable<AlgorithmListDTO>))]
        public async Task<IActionResult> GetAll()
        {
            return Ok(await _algoFacade.GetAll());
        }

        /// <summary>
        /// Retrieve help information about given algorithm.
        /// </summary>
        /// <param name="codeName">CodeName for algorithm</param>
        /// <returns></returns>
        [HttpGet("{codeName}")]
        [Produces(typeof(ProcessResult))]
        public async Task<IActionResult> RetrieveHelp(string codeName)
        {
            var result = await _runFacade.RunHelpAsync(codeName);

            return Ok(result);
        }
    }
}

src/CVaS.Web/Controllers/Web/PresentationController.cs
using System.Globalization;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using CVaS.BL.Facades;
using CVaS.BL.Helpers;
using CVaS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Razor;
using Microsoft.AspNetCore.Mvc.ViewEngines;
using CVaS.BL.Providers;

namespace CVaS.Web.Controllers.Web
{
    public class PresentationController : WebController
    {
        private readonly AlgorithmFacade _algorithmFacade;
        private readonly IRazorViewEngine _viewEngine;

        public PresentationController(ICurrentUserProvider currentUserProvider, AlgorithmFacade algoFacade, IRazorViewEngine viewEngine)
            : base(currentUserProvider)
        {
            _algorithmFacade = algoFacade;
            _viewEngine = viewEngine;
        }

        public IActionResult Upload()
        {
            var layout = new LayoutViewModel
            {
                Title = "Upload Files"
            };

            return View(InitializeLayoutModel(layout));
        }

        public async Task<IActionResult> Algorithms(string id)
        {
            if (string.IsNullOrWhiteSpace(id))
            {
                return NotFound();
            }

            var algorithm = await _algorithmFacade.Get(id);

            var viewName = Regex.Replace(algorithm.CodeName.Replace('-', ' ').ToTitleCase(), @"\s+", "");

            if (!ViewExists(viewName))
            {
                return NotFound();
            }

            var layout = new LayoutViewModel
            {
                Title = algorithm.Title
            };

            return View(viewName, InitializeLayoutModel(layout));
        }

        private bool ViewExists(string name)
        {
            ViewEngineResult result = _viewEngine.FindView(ControllerContext, name, false);
            return (result.View != null);
        }

    }
}

src/CVaS.Web/Views/Presentation/AgeDetection.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for age detection in images by <a target="_blank" href="http://www.openu.ac.il/home/hassner/projects/cnn_agegender/">Gil Levi, Tal Hassner</a></p>

<h3>API</h3>
<div class="well well-lg">
    <h4>Input</h4>
    <span>Single image with person</span><br />
    <span>Example: &quot;local://6762da80-d1e5-46a2-3818-08d472d3e445&quot;</span>

    <h4>Return</h4>
    <span>Text with range of years</span>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            return file;
        }

        var client = new AlgorithmClient('/algorithms/age-detection', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/Algorithms.cshtml
@{
    ViewData["Title"] = "Sample Algorithm: License Plate Recognition";
}

@section header {

}




<h2>@ViewData["Title"]</h2>
<div class="row">
    <div class="col-md-4">
        <form id="algorithm-run">
            <div class="form-group">
                <label for="inputFileId">Input File Id</label>
                <input type="number" class="form-control" id="inputFileId" aria-describedby="fileIdHelp" placeholder="Enter file id">
                <small id="fileIdHelp" class="form-text text-muted">Specify id of uploaded file via <a asp-controller="Presentation" asp-action="Upload">Upload File</a>.</small>
            </div>
            <fieldset class="form-group">
                <legend>Specify license plate region</legend>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="euRadioOption" value="eu" checked>
                        EU
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="usRadioOption" value="us">
                        US
                    </label>
                </div>
            </fieldset>
            <button type="submit" class="btn btn-primary" onclick="">Run</button>
        </form>
    </div>
    <div class="col-md-8">
        <p>Algorithm result:</p>
        <ol id="algorithm-result"></ol>
    </div>
</div>

@section Scripts {
    <environment names="Development">
        <script src="~/lib/fine-uploader/dist/jquery.fine-uploader.js"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="~/lib/fine-uploader/dist/jquery.fine-uploader.min.js"></script>
    </environment>

    <script>
        var showResult = function (result) {
            result = $.trim(result).length === 0 ? '&lt;empty output&gt;' : result;
            $('#algorithm-result').append('<li>' + result + '</li>');
        };

        $('#algorithm-run')
            .submit(function(e) {

                var url = '/algorithms/license-plate-recognition';

                var form = $(this);
                var requestBody = [{ c: form.find('input[type=radio]:checked').val() }, "local://" + form.find('#inputFileId').val()];
                $.ajax({
                    type: 'POST',
                    url: url,
                    data: JSON.stringify(requestBody),
                    contentType: 'application/json',
                    success: function(data) {
                        showResult(data.stdOut);
                    }
                });

                e.preventDefault(); // avoid to execute the actual submit of the form.
            });
    </script>
}

src/CVaS.Web/Views/Presentation/Colorization.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for colorful image colorization in images by <a target="_blank" href="http://richzhang.github.io/colorization/">Richard Zhang, Phillip Isola, Alexei A. Efros</a></p>

<h3>API</h3>
<div class="well well-lg">
    <h4>Input</h4>
    <span>Single grayscale image</span><br />
    <span>Example: &quot;local://6762da80-d1e5-46a2-3818-08d472d3e445&quot;</span>

    <h4>Return</h4>
    <span>Colorized image</span>
</div>
@section Scripts {
    <script>
        var callback = function (file) {
            return file;
        }

        var client = new AlgorithmClient('/algorithms/colorization', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/FaceDetection.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for face detection in images by <a target="_blank" href="http://opencv.org/">opencv</a> with python.</p>

<div class="well well-lg col-md-12">
    <form id="algorithm-run">
        <fieldset>
            <legend>Options</legend>

            <div class="form-group">
                <label class="control-label">Output type</label>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="text" checked>
                        Text
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="image">
                        Image
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="both">
                        Both
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label for="inputPlatesCount">Scale factor</label>
                <input type="number" class="form-control" id="inputScaleFactor" placeholder="Enter scale factor" min="1" max="10" value="1.1">
                <p class="help-block">Parameter specifying how much the image size is reduced at each image scale.</p>
            </div>
        </fieldset>
    </form>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            var form = $('#algorithm-run');
            return {"input": file, "scale": form.find('#inputScaleFactor').val(), "outputType": form.find('input[type=radio]:checked').val()};
        }

        var client = new AlgorithmClient('/algorithms/face-detection', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/GenderDetection.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for gender detection in images by <a target="_blank" href="http://www.openu.ac.il/home/hassner/projects/cnn_agegender/">Gil Levi, Tal Hassner</a></p>

<h3>API</h3>
<div class="well well-lg">
    <h4>Input</h4>
    <span>Single image with person</span><br />
    <span>Example: &quot;local://6762da80-d1e5-46a2-3818-08d472d3e445&quot;</span>

    <h4>Return</h4>
    <span>Text with detected genre</span><br />
    <span>Example: female</span>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            return file;
        }

        var client = new AlgorithmClient('/algorithms/gender-detection', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/LicensePlateRecognition.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for recognition license plate in images or videos is provided by <a target="_blank" href="https://github.com/openalpr/openalpr">OpenAlpr</a>.</p>

<div class="well well-lg col-md-12">
    <form id="algorithm-run">
        <fieldset>
            <legend>Options</legend>
            <div class="form-group">
                <label for="inputPlatesCount">Result plates count</label>
                <input type="number" class="form-control" id="inputPlatesCount" placeholder="Enter result count" min="1" max="10" value="1">
            </div>
            <div class="form-group">
                <label class="control-label">Specify license plate region</label>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="euRadioOption" value="eu" checked>
                        EU
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" id="usRadioOption" value="us">
                        US
                    </label>
                </div>
            </div>
        </fieldset>
    </form>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            var form = $('#algorithm-run');
            return [
                { c: form.find('input[type=radio]:checked').val(), n: form.find('#inputPlatesCount').val() },
                file
            ];
        }

        var client = new AlgorithmClient('/algorithms/license-plate-recognition', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/LongRunning.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Long Running for testing purpose require upload some image but doesnt do anything with that.</p>

<h3>Options</h3>

<div class="row">
    <div class="col-md-4">
        <form id="algorithm-run">
            <div class="form-group">
                <label for="inputDelayCount">Script delay count in seconds</label>
                <input type="number" class="form-control" id="inputDelayCount" placeholder="Enter delay count" min="0" max="120" value="5">
            </div>
        </form>
    </div>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            var form = $('#algorithm-run');
            return form.find('#inputDelayCount').val();
        }

        var client = new AlgorithmClient('/algorithms/long-running', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/Panorama.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for panorama of two images with <a target="_blank" href="http://opencv.org/">opencv</a> (SIFT, RANSAC) implemented in python.</p>

<h3>API</h3>
<div class="well well-lg">
    <h4>Input</h4>
    <span>Two images in array</span><br />
    <span>Example: [&quot;local://6762da80-d1e5-46a2-3818-08d472d3e445&quot; ,&quot;local://e87057a2-a3b3-4417-3819-08d472d3e445&quot;]</span>
    
    <h4>Return</h4>
    <span>Panorama</span>
</div>

@section Scripts {
    <script>
        var uploadedFiles = []
        var callback = function (file) {
            uploadedFiles.push(file)

            if (uploadedFiles.length == 2) { 
                array = uploadedFiles;
                uploadedFiles = [];
                return array;
            }

            return null;
        }

        var client = new AlgorithmClient('/algorithms/panorama', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/Similarity.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for similarity of two images by <a target="_blank" href="http://opencv.org/">opencv</a> with python.</p>

<h3>API</h3>
<div class="well well-lg">
    <h4>Input</h4>
    <span>Two images in array</span><br />
    <span>Example: [&quot;local://6762da80-d1e5-46a2-3818-08d472d3e445&quot; ,&quot;local://e87057a2-a3b3-4417-3819-08d472d3e445&quot;]</span>
    
    <h4>Return</h4>
    <span>JSON object with properties:</span>
    <ul>
        <li>histogram: 1.0 for identical images, less than 1.0 if images differs</li>
        <li>featureDescriptor: 0.0 for identical images, more than 0.0 if images differs</li>
    </ul>
</div>

@section Scripts {
    <script>
        var uploadedFiles = []
        var callback = function (file) {
            uploadedFiles.push(file)

            if (uploadedFiles.length == 2) { 
                array = uploadedFiles;
                uploadedFiles = [];
                return array;
            }

            return null;
        }

        var client = new AlgorithmClient('/algorithms/similarity', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/TextRecognition.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for text recognitionin images is provided by <a target="_blank" href="https://github.com/tesseract-ocr/tesseract">Tesseract OCR</a>.</p>


<div class="well well-lg col-md-12">
    <form id="algorithm-run">
        <fieldset>
            <legend>Options</legend>
            <div class="form-group">
                <label class="control-label">Specify language</label>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input" name="optionscheckboxes" id="engcheckboxOption" value="eng" checked>
                        ENG
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input" name="optionscheckboxes" id="cescheckboxOption" value="ces">
                        CES
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="checkbox" class="form-check-input" name="optionscheckboxes" id="deucheckboxOption" value="deu">
                        DEU
                    </label>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label">Page segmentation modes</label>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="3" checked>
                        Fully automatic page segmentation, but no OSD. (Default)
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="4">
                        Assume a single column of text of variable sizes.
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="5">
                        Assume a single uniform block of vertically aligned text.
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="6">
                        Assume a single uniform block of text.
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="7">
                        Treat the image as a single text line.
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="8">
                        Treat the image as a single word.
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="9">
                        Treat the image as a single word in a circle.
                    </label>
                </div>
                <div class="form-check">
                    <label class="form-check-label">
                        <input type="radio" class="form-check-input" name="optionsRadios" value="10">
                        Treat the image as a single character.
                    </label>
                </div>
            </div>
        </fieldset>
    </form>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            var form = $('#algorithm-run');
            return [
                file,
                "stdout",
                {
                    l: form.find('input[type=checkbox]:checked').map(function () { return $(this).val(); }).get().join('+'),
                    psm: form.find('input[type=radio]:checked').val()
                }
            ];
        }

        var client = new AlgorithmClient('/algorithms/text-recognition', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/ToGrayscale.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for converting to grayscale in images by <a target="_blank" href="http://opencv.org/">opencv</a> with python.</p>


@section Scripts {
    <script>
        var callback = function (file) {
            return file;
        }

        var client = new AlgorithmClient('/algorithms/to-grayscale', callback);
    </script>
}

src/CVaS.Web/Views/Presentation/VideoStabilization.cshtml
@model CVaS.Web.Models.LayoutViewModel
@{
    Layout = "_AlgorithmLayout";
}

<h3>Description</h3>
<p>Algorithm for video stabilization is provided created with <a target="_blank" href="https://ffmpeg.org/">FFmpeg</a> filters.</p>

<img src="https://trac.ffmpeg.org/ffmpeg-logo.png" alt="ffmpeg logo" style="float:right;margin-top:-100px;" />

<h3>API</h3>
<div class="well well-lg">
    <h4>Input</h4>
    <span>Video file</span><br />
    <span>Example: &quot;local://6762da80-d1e5-46a2-3818-08d472d3e445&quot;</span>
    
    <h4>Return</h4>
    <span>Stabilized video file</span>
    <ul>
</div>

@section Scripts {
    <script>
        var callback = function (file) {
            var form = $('#algorithm-run');
            return file;
        }

        var client = new AlgorithmClient('/algorithms/video-stabilization', callback, {allowedExtensions: ['avi', 'mp4']});
    </script>
}