src/CVaS.Web/Models/LayoutViewModel.cs
using System.Collections.Generic;
using CVaS.BL.DTO;
using CVaS.Web.Models.AccountViewModels;

namespace CVaS.Web.Models
{
    public class LayoutViewModel
    {
        public bool SignedIn { get; set; }

        public string CurrentUserName { get; set; }

        public string Title { get; set; }

        public string ReturnUrl { get; set; }
    }

    public class AdminSectionViewModel : LayoutViewModel
    {
        public List<AlgorithmStatsListDTO> Algorithms { get; set; }
        public List<RuleDTO> Rules { get; set; }
        public RuleViewModel NewRule { get; set; }
        public StatsDTO Stats { get; set; }
    }
}

src/CVaS.Web/ViewComponents/MenuPanelViewComponent.cs
using CVaS.BL.Providers;
using CVaS.DAL.Model;
using CVaS.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace CVaS.Web.ViewComponents
{
    public class MenuPanelViewComponent : ViewComponent
    {
        private readonly ICurrentUserProvider _currentUserProvider;
        public MenuPanelViewComponent(ICurrentUserProvider currentUserProvider)
        {
            _currentUserProvider = currentUserProvider;
        }

        public IViewComponentResult Invoke()
        {
            var login = new LoginPanelViewModel()
            {
                SignedIn = _currentUserProvider.Exists,
                CurrentUserName = _currentUserProvider.UserName,
                IsAdmin = _currentUserProvider.IsInRole(Roles.Admin)
            };
        
            return View(login);
        }
    }
}

src/CVaS.Web/ViewComponents/WebServiceStatusViewComponent.cs
using CVaS.Shared.Options;
using CVaS.Shared.Services.Broker;
using CVaS.Web.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using System.Threading.Tasks;

namespace CVaS.Web.ViewComponents
{
    public class WebServiceStatusViewComponent : ViewComponent
    {
        private readonly IBrokerStatus _brokerStatus;
        private readonly IOptions<ModeOptions> _modeOptions;

        public WebServiceStatusViewComponent(IBrokerStatus brokerStatus, IOptions<ModeOptions> modeOptions)
        {
            _modeOptions = modeOptions;
            _brokerStatus = brokerStatus;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var algServerCount = await _brokerStatus.GetConnectedAlgServersCount();

            var status = new WebServiceStatusViewModel()
            {
                IsAnyAlgServerOnline = !algServerCount.HasValue || algServerCount.Value > 0,
                IsLocalMode = _modeOptions.Value.IsLocal
            };

            return View(status);
        }
    }
}

src/CVaS.Web/Views/Shared/_Layout.cshtml
@model CVaS.Web.Models.LayoutViewModel

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@Model.Title</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootswatch-dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://bootswatch.com/flatly/bootstrap.min.css"
              asp-fallback-href="~/lib/bootswatch-dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
    </environment>
    @RenderSection("header", required: false)

    <environment include="Development">
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>

    <authorize roles="Admin">
        <vc:web-service-status />
    </authorize>

    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#items-navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Computer Vision as a Service</a>
            </div>
            <div class="collapse navbar-collapse" id="items-navbar-collapse">
                <vc:menu-panel />
            </div>
        </div>
    </nav>
    <div class="container body-content">
        <div class="clearfix">
            @RenderBody()
        </div>
        <hr />
        <footer>
            <p>&copy; 2016 - 2017 Adam Jež</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootswatch-dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootswatch-dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
    <environment names="Development">
        <mini-profiler position="@RenderPosition.Right" max-traces="10" start-hidden="false" />
    </environment>
</body>
</html>